name: grid_space
description: Handles the state of a page containing grid content and constrains a child widget such that it's width will match the grid width
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
